image: alpine/edge
packages:
  - deno
  - unzip
  - curl
secrets:
  - 1395de5b-a4f1-452a-9825-5e82a18d656c
sources:
  - https://git.sr.ht/~jordanreger/htmlsky#ts
tasks:
  - install-deployctl: |
      deno install -Arf jsr:@deno/deployctl
  - deploy: |
      set +x
      export DENO_DEPLOY_TOKEN=$(cat ~/.deno_deploy_token)
      set -x
      export DENO_INSTALL="/home/build/.deno"
      export PATH="$DENO_INSTALL/bin:$PATH"
      cd htmlsky
      deployctl deploy --prod
