image: alpine/latest
packages:
  - unzip
sources:
  - https://git.sr.ht/~jordanreger/htmlsky#ts
environment:
  DENO_INSTALL: /home/build/.deno
  PATH: $DENO_INSTALL/bin:$PATH
tasks:
  - install-deno: |
      curl -fsSL https://deno.land/x/install/install.sh | sh
  - install-deployctl: |
      deno install -Arf jsr:@deno/deployctl
  - deploy: |
      deployctl deploy
