image: alpine/edge
packages:
  - curl
secrets:
  - 156cbb78-ab98-46a6-8b2a-6c74714ec4b9
sources:
  - https://git.sr.ht/~jordanreger/htmlsky
tasks:
  - install-flyctl: |
      curl -L https://fly.io/install.sh | sh
  - deploy: |
      set +x
      export FLY_API_TOKEN=$(cat ~/.fly_token)
      set -x

      export FLYCTL_INSTALL="/home/build/.fly"
      export PATH="$FLYCTL_INSTALL/bin:$PATH"
      flyctl deploy --remote-only ./htmlsky
